---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: kube-system
  name: ofss
spec:
  replicas: 1
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - operator: DoesNotExist
                    key: node-role.kubernetes.io/master
      containers:
        - terminationMessagePath: /dev/termination-log
          name: ofss
          securityContext: 
            privileged: true
          image: 'registry.cn-hangzhou.aliyuncs.com/sourcegarden/openvpn-fss:v0.2'
          terminationMessagePolicy: File
          env:
            - name: server_addr
              value: bbs.itaojin.me
            - name: hostname_in_docker
              value: daocloud-k8s-sh
            - name: ip_out_docker
              value: 10.25.10.20
            - name: ssh_port_out_docker
              value: '22'
            - name: TZ
              value: Asia/Chongqing
          imagePullPolicy: Always
          resources:
            requests:
              memory: '0'
            limits:
              cpu: '1'
              memory: '1G'
          volumeMounts:
          - mountPath: /etc/openvpn
            name: data-ofss-openvpn
          - mountPath: /var/run/docker.sock
            name: docker-socket
      volumes:
      - name: data-ofss-openvpn
        hostPath:
          path: /data/tools/ofss/openvpn
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock